
package ataques;

public enum TipoEfeito {

    STATUS, //CONGELADO, PARALIZADO...
    ATAQUE, //SANGRAMENTO, VENENO, CHAMAS...
    BUFF, //REGENERAÇÃO, FORÇA...
    DEBUFF //FRAQUEZA, LENTIDÃO...

}